-- MySQL Script generated by MySQL Workbench
-- Wed Aug 27 14:22:39 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema new_sso
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema new_sso
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `new_sso` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `new_sso` ;

-- -----------------------------------------------------
-- Table `new_sso`.`organizations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `new_sso`.`organizations` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `url` VARCHAR(255) NOT NULL,
  `shared_user_applications` TINYINT(1) NOT NULL DEFAULT '0',
  `settings` JSON NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `organizations_name_unique` (`name` ASC) VISIBLE,
  UNIQUE INDEX `organizations_url_unique` (`url` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `new_sso`.`sso_applications`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `new_sso`.`sso_applications` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `organization_id` BIGINT UNSIGNED NOT NULL,
  `application_name` VARCHAR(255) NOT NULL,
  `application_url` VARCHAR(500) NOT NULL,
  `client_id` VARCHAR(255) NOT NULL,
  `client_secret` VARCHAR(255) NOT NULL,
  `redirect_uri` VARCHAR(500) NOT NULL,
  `scope` TEXT NULL DEFAULT NULL,
  `status` ENUM('active', 'disabled') NOT NULL DEFAULT 'active',
  `allowed_origins` TEXT NULL DEFAULT NULL,
  `token_expiration_time` INT NOT NULL DEFAULT '3600',
  `refresh_token_enabled` TINYINT(1) NOT NULL DEFAULT '1',
  `refresh_token_expiration_time` INT NOT NULL DEFAULT '3600',
  `description` TEXT NULL DEFAULT NULL,
  `logo_url` VARCHAR(500) NULL DEFAULT NULL,
  `mode_strict` INT NULL DEFAULT '0',
  `whitelist` TEXT NULL DEFAULT NULL,
  `callback_url` TEXT NULL DEFAULT NULL,
  `webhook_url` VARCHAR(500) NULL DEFAULT NULL,
  `webhook_secret` VARCHAR(255) NULL DEFAULT NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `sso_applications_client_id_key` (`client_id` ASC) VISIBLE,
  UNIQUE INDEX `apps_org_name_unique` (`organization_id` ASC, `application_name` ASC) VISIBLE,
  CONSTRAINT `fk_apps_org`
    FOREIGN KEY (`organization_id`)
    REFERENCES `new_sso`.`organizations` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `new_sso`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `new_sso`.`users` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `organization_id` BIGINT UNSIGNED NOT NULL,
  `identify` VARCHAR(255) NULL DEFAULT NULL,
  `username` VARCHAR(64) NULL DEFAULT NULL,
  `full_name` JSON NULL DEFAULT NULL,
  `first_name` JSON NULL DEFAULT NULL,
  `last_name` JSON NULL DEFAULT NULL,
  `avatar` VARCHAR(500) NULL DEFAULT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `phone` VARCHAR(20) NULL DEFAULT NULL,
  `phone_code` VARCHAR(5) NULL DEFAULT NULL,
  `identify_verified_at` TIMESTAMP NULL DEFAULT NULL,
  `email_verified_at` TIMESTAMP NULL DEFAULT NULL,
  `phone_verified_at` TIMESTAMP NULL DEFAULT NULL,
  `password` VARCHAR(255) NULL DEFAULT NULL,
  `role` TINYINT(1) NOT NULL DEFAULT '0',
  `type` TINYINT(1) NOT NULL DEFAULT '0',
  `passport_image` VARCHAR(255) NULL DEFAULT NULL,
  `gravatar` TEXT NULL DEFAULT NULL,
  `data` TEXT NULL DEFAULT NULL,
  `hash` TEXT NULL DEFAULT NULL,
  `method` VARCHAR(100) NULL DEFAULT NULL,
  `service` VARCHAR(100) NULL DEFAULT NULL,
  `status` INT NULL DEFAULT NULL,
  `date_of_birth` DATE NULL DEFAULT NULL,
  `nationality` VARCHAR(255) NULL DEFAULT NULL,
  `country` CHAR(2) NULL DEFAULT NULL,
  `nationality_code` CHAR(2) NULL DEFAULT NULL,
  `two_factor_enabled` TINYINT(1) NULL DEFAULT '0',
  `two_factor_secret` VARCHAR(255) NULL DEFAULT NULL,
  `email_2fa` INT NULL DEFAULT '0',
  `email_2fa_secret` VARCHAR(32) NULL DEFAULT '',
  `ga_2fa` INT NULL DEFAULT '0',
  `ga_2fa_secret` VARCHAR(32) NULL DEFAULT '',
  `remember_token` VARCHAR(100) NULL DEFAULT NULL,
  `timezone` VARCHAR(100) NULL DEFAULT NULL,
  `language` VARCHAR(10) NULL DEFAULT 'en',
  `last_login_at` DATETIME(3) NULL DEFAULT NULL,
  `last_login_ip` VARCHAR(45) NULL DEFAULT NULL,
  `login_attempts` INT NULL DEFAULT '0',
  `locked_until` DATETIME(3) NULL DEFAULT NULL,
  `password_changed_at` DATETIME(3) NULL DEFAULT NULL,
  `idp_data` JSON NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `full_name_en` VARCHAR(255) GENERATED ALWAYS AS (json_unquote(json_extract(`full_name`,_utf8mb4'$.en'))) STORED,
  `full_name_ar` VARCHAR(255) GENERATED ALWAYS AS (json_unquote(json_extract(`full_name`,_utf8mb4'$.ar'))) STORED,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `users_org_email_unique` (`organization_id` ASC, `email` ASC) VISIBLE,
  UNIQUE INDEX `users_org_username_unique` (`organization_id` ASC, `username` ASC) VISIBLE,
  UNIQUE INDEX `users_org_identify_unique` (`organization_id` ASC, `identify` ASC) VISIBLE,
  INDEX `users_org_idx` (`organization_id` ASC) VISIBLE,
  INDEX `users_last_login_at_idx` (`last_login_at` ASC) VISIBLE,
  INDEX `users_status_idx` (`status` ASC) VISIBLE,
  INDEX `users_full_name_en_idx` (`full_name_en` ASC) VISIBLE,
  INDEX `users_full_name_ar_idx` (`full_name_ar` ASC) VISIBLE,
  CONSTRAINT `fk_users_org`
    FOREIGN KEY (`organization_id`)
    REFERENCES `new_sso`.`organizations` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `new_sso`.`authorization_codes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `new_sso`.`authorization_codes` (
  `id` VARCHAR(191) NOT NULL,
  `code` VARCHAR(255) NOT NULL,
  `user_id` BIGINT UNSIGNED NOT NULL,
  `sso_application_id` BIGINT UNSIGNED NOT NULL,
  `redirect_uri` VARCHAR(500) NOT NULL,
  `scope` VARCHAR(255) NOT NULL,
  `expires_at` DATETIME(3) NOT NULL,
  `used_at` DATETIME(3) NULL DEFAULT NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `authorization_codes_code_key` (`code` ASC) VISIBLE,
  INDEX `authorization_codes_user_id_fkey` (`user_id` ASC) VISIBLE,
  INDEX `authorization_codes_sso_application_id_fkey` (`sso_application_id` ASC) VISIBLE,
  INDEX `authorization_codes_user_app_exp_idx` (`user_id` ASC, `sso_application_id` ASC, `expires_at` ASC) VISIBLE,
  CONSTRAINT `authorization_codes_sso_application_id_fkey`
    FOREIGN KEY (`sso_application_id`)
    REFERENCES `new_sso`.`sso_applications` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `authorization_codes_user_id_fkey`
    FOREIGN KEY (`user_id`)
    REFERENCES `new_sso`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `new_sso`.`failed_jobs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `new_sso`.`failed_jobs` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(255) NOT NULL,
  `connection` TEXT NOT NULL,
  `queue` TEXT NOT NULL,
  `payload` LONGTEXT NOT NULL,
  `exception` LONGTEXT NOT NULL,
  `failed_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `failed_jobs_uuid_unique` (`uuid` ASC) VISIBLE,
  INDEX `failed_jobs_failed_at_idx` (`failed_at` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `new_sso`.`jobs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `new_sso`.`jobs` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `queue` VARCHAR(255) NOT NULL,
  `payload` LONGTEXT NOT NULL,
  `attempts` TINYINT UNSIGNED NOT NULL,
  `reserved_at` INT UNSIGNED NULL DEFAULT NULL,
  `available_at` INT UNSIGNED NOT NULL,
  `created_at` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `jobs_queue_index` (`queue` ASC) VISIBLE,
  INDEX `jobs_available_idx` (`available_at` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `new_sso`.`last_logins`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `new_sso`.`last_logins` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT UNSIGNED NOT NULL,
  `ip_address` VARCHAR(45) NOT NULL,
  `user_agent` TEXT NULL DEFAULT NULL,
  `location` VARCHAR(255) NULL DEFAULT NULL,
  `device` VARCHAR(255) NULL DEFAULT NULL,
  `browser` VARCHAR(255) NULL DEFAULT NULL,
  `os` VARCHAR(255) NULL DEFAULT NULL,
  `attempt` INT NOT NULL DEFAULT '1',
  `successful` TINYINT(1) NOT NULL DEFAULT '1',
  `failure_reason` VARCHAR(255) NULL DEFAULT NULL,
  `login_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  INDEX `last_logins_user_id_fkey` (`user_id` ASC) VISIBLE,
  INDEX `last_logins_user_time_idx` (`user_id` ASC, `login_at` ASC) VISIBLE,
  CONSTRAINT `last_logins_user_id_fkey`
    FOREIGN KEY (`user_id`)
    REFERENCES `new_sso`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `new_sso`.`menus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `new_sso`.`menus` (
  `id` VARCHAR(191) NOT NULL,
  `name` VARCHAR(100) NULL DEFAULT NULL,
  `title` VARCHAR(255) NOT NULL,
  `url` VARCHAR(500) NOT NULL,
  `icon` VARCHAR(100) NULL DEFAULT NULL,
  `position` INT NOT NULL DEFAULT '0',
  `parent_id` VARCHAR(191) NULL DEFAULT NULL,
  `status` ENUM('active', 'hidden', 'disabled') NOT NULL DEFAULT 'active',
  `target` VARCHAR(20) NOT NULL DEFAULT '_self',
  `css_class` VARCHAR(100) NULL DEFAULT NULL,
  `role` VARCHAR(100) NULL DEFAULT NULL,
  `permissions` TEXT NULL DEFAULT NULL,
  `group` VARCHAR(100) NULL DEFAULT NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `menus_parent_id_fkey` (`parent_id` ASC) VISIBLE,
  CONSTRAINT `menus_parent_id_fkey`
    FOREIGN KEY (`parent_id`)
    REFERENCES `new_sso`.`menus` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `new_sso`.`permissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `new_sso`.`permissions` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `sso_application_id` BIGINT UNSIGNED NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `guard_name` VARCHAR(255) NULL DEFAULT NULL,
  `frontend` TINYINT(1) NOT NULL DEFAULT '0',
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `permissions_name_sso_application_id_unique` (`name` ASC, `sso_application_id` ASC) VISIBLE,
  INDEX `permissions_sso_application_id_foreign` (`sso_application_id` ASC) VISIBLE,
  CONSTRAINT `permissions_sso_application_id_foreign`
    FOREIGN KEY (`sso_application_id`)
    REFERENCES `new_sso`.`sso_applications` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `new_sso`.`model_has_permissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `new_sso`.`model_has_permissions` (
  `permission_id` BIGINT UNSIGNED NOT NULL,
  `sso_application_id` BIGINT UNSIGNED NOT NULL,
  `model_type` VARCHAR(255) NOT NULL,
  `model_id` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`permission_id`, `model_id`, `model_type`, `sso_application_id`),
  INDEX `model_has_permissions_model_id_model_type_index` (`model_id` ASC, `model_type` ASC) VISIBLE,
  INDEX `fk_mhp_app` (`sso_application_id` ASC) VISIBLE,
  INDEX `model_has_permissions_model_id_model_type_idx` (`model_id` ASC, `model_type` ASC) VISIBLE,
  CONSTRAINT `fk_mhp_app`
    FOREIGN KEY (`sso_application_id`)
    REFERENCES `new_sso`.`sso_applications` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `model_has_permissions_permission_id_foreign`
    FOREIGN KEY (`permission_id`)
    REFERENCES `new_sso`.`permissions` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `new_sso`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `new_sso`.`roles` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `guard_name` VARCHAR(255) NULL DEFAULT NULL,
  `sso_application_id` BIGINT UNSIGNED NOT NULL,
  `frontend` TINYINT(1) NOT NULL DEFAULT '0',
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `roles_name_sso_application_id_unique` (`name` ASC, `sso_application_id` ASC) VISIBLE,
  INDEX `roles_sso_application_id_foreign` (`sso_application_id` ASC) VISIBLE,
  CONSTRAINT `roles_sso_application_id_foreign`
    FOREIGN KEY (`sso_application_id`)
    REFERENCES `new_sso`.`sso_applications` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `new_sso`.`model_has_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `new_sso`.`model_has_roles` (
  `role_id` BIGINT UNSIGNED NOT NULL,
  `sso_application_id` BIGINT UNSIGNED NOT NULL,
  `model_type` VARCHAR(255) NOT NULL,
  `model_id` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`role_id`, `model_id`, `model_type`, `sso_application_id`),
  INDEX `model_has_roles_model_id_model_type_index` (`model_id` ASC, `model_type` ASC) VISIBLE,
  INDEX `fk_mhr_app` (`sso_application_id` ASC) VISIBLE,
  INDEX `model_has_roles_model_id_model_type_idx` (`model_id` ASC, `model_type` ASC) VISIBLE,
  CONSTRAINT `fk_mhr_app`
    FOREIGN KEY (`sso_application_id`)
    REFERENCES `new_sso`.`sso_applications` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `model_has_roles_role_id_foreign`
    FOREIGN KEY (`role_id`)
    REFERENCES `new_sso`.`roles` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `new_sso`.`oauth_connections`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `new_sso`.`oauth_connections` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT UNSIGNED NOT NULL,
  `provider` VARCHAR(50) NOT NULL,
  `provider_id` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `avatar` VARCHAR(500) NULL DEFAULT NULL,
  `access_token` TEXT NULL DEFAULT NULL,
  `refresh_token` TEXT NULL DEFAULT NULL,
  `token_expires_at` DATETIME(3) NULL DEFAULT NULL,
  `scope` TEXT NULL DEFAULT NULL,
  `profile_data` TEXT NULL DEFAULT NULL,
  `connected_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `last_used_at` DATETIME(3) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `oauth_connections_user_id_provider_key` (`user_id` ASC, `provider` ASC) VISIBLE,
  UNIQUE INDEX `oauth_provider_account_unique` (`provider` ASC, `provider_id` ASC) VISIBLE,
  CONSTRAINT `oauth_connections_user_id_fkey`
    FOREIGN KEY (`user_id`)
    REFERENCES `new_sso`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `new_sso`.`password_reset_tokens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `new_sso`.`password_reset_tokens` (
  `user_id` BIGINT UNSIGNED NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `token` VARCHAR(255) NOT NULL,
  `used_at` DATETIME(3) NULL DEFAULT NULL,
  `ip_address` VARCHAR(45) NULL DEFAULT NULL,
  `user_agent` TEXT NULL DEFAULT NULL,
  `expired_at` DATETIME(3) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`user_id`, `token`),
  UNIQUE INDEX `forgot_passwords_token_key` (`token` ASC) VISIBLE,
  INDEX `forgot_passwords_user_id_fkey` (`email` ASC) VISIBLE,
  INDEX `password_reset_tokens_used_idx` (`used_at` ASC) VISIBLE,
  CONSTRAINT `fk_prt_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `new_sso`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `new_sso`.`personal_access_tokens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `new_sso`.`personal_access_tokens` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `tokenable_type` VARCHAR(255) NOT NULL,
  `tokenable_id` BIGINT UNSIGNED NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `token` VARCHAR(64) NOT NULL,
  `abilities` TEXT NULL DEFAULT NULL,
  `last_used_at` TIMESTAMP NULL DEFAULT NULL,
  `expires_at` TIMESTAMP NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `personal_access_tokens_token_unique` (`token` ASC) VISIBLE,
  INDEX `personal_access_tokens_tokenable_type_tokenable_id_index` (`tokenable_type` ASC, `tokenable_id` ASC) VISIBLE,
  INDEX `personal_tokens_expires_idx` (`expires_at` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `new_sso`.`refresh_tokens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `new_sso`.`refresh_tokens` (
  `id` VARCHAR(191) NOT NULL,
  `token` VARCHAR(255) NOT NULL,
  `user_id` BIGINT UNSIGNED NOT NULL,
  `sso_application_id` BIGINT UNSIGNED NOT NULL,
  `scope` VARCHAR(255) NOT NULL,
  `expires_at` DATETIME(3) NOT NULL,
  `revoked` TINYINT(1) NOT NULL DEFAULT '0',
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `refresh_tokens_token_key` (`token` ASC) VISIBLE,
  INDEX `refresh_tokens_user_id_fkey` (`user_id` ASC) VISIBLE,
  INDEX `refresh_tokens_sso_application_id_fkey` (`sso_application_id` ASC) VISIBLE,
  INDEX `refresh_tokens_expires_idx` (`expires_at` ASC) VISIBLE,
  CONSTRAINT `refresh_tokens_sso_application_id_fkey`
    FOREIGN KEY (`sso_application_id`)
    REFERENCES `new_sso`.`sso_applications` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `refresh_tokens_user_id_fkey`
    FOREIGN KEY (`user_id`)
    REFERENCES `new_sso`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `new_sso`.`role_has_permissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `new_sso`.`role_has_permissions` (
  `permission_id` BIGINT UNSIGNED NOT NULL,
  `role_id` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`permission_id`, `role_id`),
  INDEX `role_has_permissions_role_id_foreign` (`role_id` ASC) VISIBLE,
  CONSTRAINT `role_has_permissions_permission_id_foreign`
    FOREIGN KEY (`permission_id`)
    REFERENCES `new_sso`.`permissions` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `role_has_permissions_role_id_foreign`
    FOREIGN KEY (`role_id`)
    REFERENCES `new_sso`.`roles` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `new_sso`.`saml2_tenants`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `new_sso`.`saml2_tenants` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `application_id` BIGINT UNSIGNED NOT NULL,
  `uuid` CHAR(36) NOT NULL,
  `key` VARCHAR(255) NULL DEFAULT NULL,
  `idp_entity_id` VARCHAR(255) NOT NULL,
  `idp_login_url` VARCHAR(255) NOT NULL,
  `idp_logout_url` VARCHAR(255) NOT NULL,
  `idp_x509_cert` TEXT NOT NULL,
  `metadata` JSON NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `relay_state_url` VARCHAR(255) NULL DEFAULT NULL,
  `name_id_format` VARCHAR(255) NOT NULL DEFAULT 'persistent',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `saml2_tenants_uuid_unique` (`uuid` ASC) VISIBLE,
  INDEX `fk_saml_tenant_app` (`application_id` ASC) VISIBLE,
  CONSTRAINT `fk_saml_tenant_app`
    FOREIGN KEY (`application_id`)
    REFERENCES `new_sso`.`sso_applications` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `new_sso`.`webhook_logs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `new_sso`.`webhook_logs` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `sso_application_id` BIGINT UNSIGNED NOT NULL,
  `event_id` VARCHAR(100) NOT NULL,
  `event_key` VARCHAR(100) NOT NULL,
  `event_type` VARCHAR(100) NULL DEFAULT NULL,
  `event_name` VARCHAR(100) NULL DEFAULT NULL,
  `event_owner` VARCHAR(64) NULL DEFAULT NULL,
  `event_data` TEXT NULL DEFAULT NULL,
  `payload` TEXT NOT NULL,
  `response` TEXT NULL DEFAULT NULL,
  `status` VARCHAR(50) NOT NULL,
  `http_status_code` INT NULL DEFAULT NULL,
  `endpoint` TEXT NULL DEFAULT NULL,
  `http_status` INT NULL DEFAULT NULL,
  `http_response` TEXT NULL DEFAULT NULL,
  `attempt` INT NOT NULL DEFAULT '1',
  `error_message` TEXT NULL DEFAULT NULL,
  `delivered_at` DATETIME(3) NULL DEFAULT NULL,
  `next_retry_at` DATETIME(3) NULL DEFAULT NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  INDEX `webhook_logs_sso_application_id_fkey` (`sso_application_id` ASC) VISIBLE,
  INDEX `index_log_webhooks` (`event_key` ASC, `event_owner` ASC) VISIBLE,
  INDEX `webhook_logs_app_created_idx` (`sso_application_id` ASC, `created_at` ASC) VISIBLE,
  INDEX `webhook_logs_status_idx` (`status` ASC) VISIBLE,
  CONSTRAINT `webhook_logs_sso_application_id_fkey`
    FOREIGN KEY (`sso_application_id`)
    REFERENCES `new_sso`.`sso_applications` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
